# Use the official .NET SDK image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

# Set the working directory
WORKDIR /app

# Copy the project files and restore any dependencies
COPY backend.csproj ./
RUN dotnet restore

# Copy the rest of the application
COPY . ./

# Expose the port the application runs on
EXPOSE 5243

# Set the entrypoint to use dotnet watch for hot reloading
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5243"]